config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'test' => 'message#cable'

  get '/message/newcomming'  => 'message#newcomming'
  get '/message/:id' => 'message#show', as: :message_show
  get '/mail/update' => 'ajax#updateEmails',  defaults: {format: 'json'}
  root 'message#inbox'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
end

app/models/email_address.rb
class EmailAddress < ApplicationRecord
  validates_uniqueness_of :local_part, :scope => :domain_id

  belongs_to :domain

  def self.create_random(domain_id = 1)
    o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
    string = (0...10).map { o[rand(o.length)] }.join

    self::create!(domain_id: domain_id, local_part: string)

    rescue ActiveRecord::RecordInvalid
      retry
  end

  def address
    self.local_part + '@' + self.domain.name
  end

  def messages
    Message.where(message_to: self.address)
  end
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
    include MailLogHelper 

    def updateEmails
        emailAddress = params[:email]
        email =  MailLog.where(to: emailAddress).last
        respond_to do |format|
            # if the response fomat is html, redirect as usua
            if email
                if email.created_at < Time.now - 1.minute
                    @mailLogs = MailLog.where("to = ? and created_at > ?", emailAddress,  Time.now - 1.minute)
                    if @mailLogs
                        template = generateHtmlForAjax(@mailLogs)

                    end
                    format.json { render json: [
                        'error' => true,
                        'result' => template

                    ] }       

                else
                    format.json { render json: [
                        'error' => true,
                        'message' => 'no new mail'

                    ] }    
                end
            else
                format.json { render json: [
                    'error' => true,
                    'message' => 'email not found'
                ] }
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_email_address
  before_action :set_locale

  def set_email_address
    if session['email']
      @email  = EmailAddress.find_by(local_part: session['email']['local_part'], domain_id: session['email']['domain_id'])
    else
      @email  = EmailAddress.create_random
      session['email'] = {
        local_part: @email.local_part,
        domain_id:  @email.domain_id
      }
    end
  end

  def set_locale
    I18n.locale = :fa
  end
end

app/controllers/mail_log_controller.rb
class MailLogController < ApplicationController

  def show
    @mailLog = MailLog.find(params[:id])
  end

  def index
    if session[:email]
      @randomEmail = session[:email]  
    else
      o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      string = (0...10).map { o[rand(o.length)] }.join
      @randomEmail = string + '@clockwise.ir'
      session[:email] = @randomEmail
    end

    @mailLogs = MailLog.where(to: "#{@randomEmail}")
  end

  def update
    emailAddress = params[:email]
    email =  MailLog.where(to: emailAddress).last
    if email
      if email.created_at < 1.minute.ago
        @mailLogs = MailLog.where(to: email)
        #respond_with
        render :update
      else
        false
      end
    end
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  
  def inbox
    @messages = Message.where(message_to: @email.address)
  end

  def show
    @message = Message.find(params[:id])
    raise 'access denied' unless @message.message_to == @email.address
  end

  def newcomming
    @messages = @email.messages

    if params[:last]
      @messages = @messages.where('id > ?', params[:last])
    end

    render json: @messages
  end

  def cable
    message = Message.last
    ActionCable.server.broadcast 'messages', message
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mail_log_helper.rb
module MailLogHelper

    def generateHtmlForAjax(mailLogs)
        result = ''
        @data = mailLogs
        if @data 
            @data.each do |mailLog|
                result = result + "
                <div class='row mailLog-item'>
                    <a href='/show/#{mailLog.id}'>
                        <div class='col-xs-2'>
                            #{mailLog.subject}
                        </div>
                        <div class='col-xs-4'>
                            #{mailLog.sender}
                        </div>
                        <div class='col-xs-4'>
                            #{mailLog.mail_date}
                        </div>
                    </a>
                </div> "   
            end
        end
        result
    end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Mail</title>
        <%= csrf_meta_tags %>
        <%= action_cable_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    </head>

    <body class="<%= t 'css.main direction' %>">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <a class="navbar-brand" href="/"> <%= t 'Arta Center'%></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <%= t 'Menu'%>
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/"><%= t 'Home'%></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><%= t 'About'%></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><%= t 'Contact'%></a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Page Header -->
        <header class="masthead" style="background-image: url('<%= asset_path 'home-bg.jpg' %>')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <div class="site-heading">
                            <h1>ARTA CENTER</h1>
                            <span class="subheading">Temporary Email</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Main Content -->
        <div class="container">
            <div class="row">
                <%= yield %>
            </div>
        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Arta Center 2017</p>
                        <p class='developer'>Developed by <a href="http://mohsen.alizadeh.us" class='link'>Mohsen Alizadeh</a></p>
                    </div>
                </div>
            </div>
        </footer>
  </body>
</html>

app/views/mail_log/update.html.slim
- if @mailLogs
    - @mailLogs.each do |mailLog|
        div  class='row mailLog-item'
            a  href='/show/#{mailLog.id}'
                div class='col-xs-2'
                    = mailLog.subject
                div class='col-xs-4'
                    = mailLog.sender
                div class='col-xs-4'
                    = mailLog.email_date

app/views/message/inbox.html.slim
div class='email-box'
  form action='/' method='post' class='temporary-email'
    span
      = t 'temporary email address'
    input typ='text' value="#{@email.address}" class='user-email'  name='user-email' readonly='readonly'
div class='inbox'
    div class='row head'
        div class='col-xs-2'
          = t 'subject'
        div class='col-xs-4'
          = t 'sender'
        div class='col-xs-4'
          = t 'date'
    hr
div class='inbox-messages'
    - @messages.each do |message|
        div  class='row message' data-id='#{message.id}'
            a  href='#{message_show_path(message)}'
              div class='row'
                div class='col-xs-2'
                    = message.message_subject
                div class='col-xs-4'
                    = message.sender_email
                div class='col-xs-4'
                    = message.updated_at.strftime('%m/%d/%Y %H:%M:%S')

app/views/message/show.html.slim
div
    div class='subject' 
        span 
           | subject:
        = @message.message_subject
    div class='send'
        span 
           | From:
        = @message.sender_email
        div class='pull-right'
            = @message.message_date
    div class='body'
        = @message.message_body